import uuid
import os
from dateutil import parser
from datetime import timezone

# fixed namespace for generating UUID v5 to ensure consistency of shift_log_id across different runs and environments.
APP_NAMESPACE = uuid.UUID(os.getenv("UUID_STRING")) 


def generate_uuid_v5(record_date, shift, line):
    """ Generate UUID v5 from record_date, shift, line """

    return str(uuid.uuid5(APP_NAMESPACE, f"{record_date}|{shift}|{line}"))


def add_shift_log_id(records):
    """
    Add shift_log_id to each record in records. shift_log_id is generated by UUID v5 using date, shift, line
    """


    for record in records:
        record_date = record.get("date")
        shift = record.get("shift")
        line = record.get("line")
        if not record_date or not shift or not line:
            continue
        record["shift_log_id"] = generate_uuid_v5(record_date, shift, line)


    return records


def split_records_by_validity(validated_records):
    """ Split records into valid and invalid records based on 'is_valid' key in each record."""
       

    valid_records = []
    invalid_records = []
    for record in validated_records:
        if record['is_valid']:
            valid_records.append(record)
        else:
            invalid_records.append(record)

    return valid_records, invalid_records


def to_iso_utc(records):
    """ 
    Convert record_date to ISO format in UTC timezone. If date is invalid, set 'date_iso' as None.

    examples:
    ******
    to_iso_utc("")              # None
    to_iso_utc("   ")           # None
    to_iso_utc(None)            # None
    to_iso_utc(12345)           # None
    to_iso_utc("invalid date")  # None
    to_iso_utc("2026-02-21")    # 2026-02-21T00:00:00Z
    ******
    """

    for record in records:
        s = record.get('date')

        # None check and type check
        if not isinstance(s, str):
            record['date_iso'] = None
            continue

        # Empty string check
        if not s.strip():
            record['date_iso'] = None
            continue

        try:
            dt = parser.parse(s)

            # if timezone info is missing, assume it's in UTC
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=timezone.utc)

            # Normalize to UTC
            dt = dt.astimezone(timezone.utc)

            record['date_iso'] = dt.isoformat()

        except (ValueError, OverflowError, TypeError):
            record['date_iso'] = None

    return records


def filter_columns(record):
    """ Drop unnecessary columns for kpi table """
    
    keys_to_drop = ("date_iso", "is_duplicate", "invalid_reason", "is_valid")
    
    for key in keys_to_drop:
        record.pop(key, None)

    return record


def build_shift_log_kpi_records(validated_records):
    """ Cauculate KPIs and build shift_log_kpi records """

    kpi_records = []

    for record in validated_records:
        if not record.get("is_valid"):
            continue

        planned_output = record["planned_output"]
        actual_output = record["actual_output"]
        defect_qty = record["defect_qty"]
        downtime_min = record["downtime_min"]

        kpi_record = record.copy()
        # Drop unnecessary columns for kpi table
        kpi_record = filter_columns(kpi_record)

        kpi_record["production_achievement"] = (
            actual_output / planned_output if planned_output else None
        )
        kpi_record["defect_rate"] = (
            defect_qty / actual_output if actual_output else None
        )
        kpi_record["downtime_rate"] = downtime_min / 480

        kpi_records.append(kpi_record)

    return kpi_records
